version: 2.1
jobs:
  build:
    docker:
      - image: chialab/php-dev:7.3-apache

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: composer install

      - run:
          name: Do tests
          command: make test